-- LANGKAH 1: Tambah Site Sinjai & Takalar
INSERT INTO oki_customer_sites (customer_id, kode_site, site_name) VALUES (2, 'SR-ESA-02', 'SR - Sinjai');
INSERT INTO oki_customer_sites (customer_id, kode_site, site_name) VALUES (2, 'SR-ESA-03', 'SR - Takalar');

-- LANGKAH 2: INSERT oki_site_ba
INSERT INTO oki_site_ba (id_site, ba_name) VALUES ((SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), 'BAI-SR') ON DUPLICATE KEY UPDATE ba_name = 'BAI-SR';
INSERT INTO oki_site_ba (id_site, ba_name) VALUES ((SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), 'BAI') ON DUPLICATE KEY UPDATE ba_name = 'BAI';
INSERT INTO oki_site_ba (id_site, ba_name) VALUES ((SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), 'BAI') ON DUPLICATE KEY UPDATE ba_name = 'BAI';

-- LANGKAH 3: UPDATE oki_perangkat - KUPANG
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'FGT80FTK23054198';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'KIT407048515BD5';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003362';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003354';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XSBL011ZV78T';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003355';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2516A03484';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2609A02514';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTZD06B8H0P9';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2516A03222';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTZD069WPXZ8';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = '3013C261700178';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTBK0134QDNK';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CJKR2PT';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD01KXLK2B';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CXGKPPJ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0BK3CMPJ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0C139JSX';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0BGT2R2W';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0DJ02DHZ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0DT5LSQZ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL09SF4RPV';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CL116XP';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL09S7SBH5';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CJNFCT4';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL09QF2ZGL';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CLGH0HX';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL09STMXPF';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CVBZ3BN';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0F2JPVZT';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0BMLN0VZ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0D802LWH';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF8N';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF7G';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF2H';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF7S';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF79';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF9A';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF93';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF8W';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF8D';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7TAF7Z';

-- LANGKAH 3: UPDATE oki_perangkat - SINJAI
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = '-';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'FGT80FTK23054167';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XSBL010828SR';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'KIT407789867VVS';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003356';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003357';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003503';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTCA0092TD4F';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2516A03218';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTCA008HLJSG';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2516A03216';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTCA002FRZWM';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2609A02504';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = '3013C261700019';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0D1D3JBK';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0B156WJC';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0B2DMDN3';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0D0TK4J2';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0DZQ7P9V';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0BDMBRFN';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL09W0PXNN';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL09VM4BRX';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0B2ZTM95';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0B9KZBJL';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0BG1R1H3';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0BGHQRGT';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CKT71G3';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0D3XWZHH';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0DTJJ99K';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL04J49X9J';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL01DGVZ31';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0234FZ4H';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0BK68223';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N4RA9PK';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7RBA97';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7RBA7N';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7RBA6S';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7PBUP6';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7RBAPW';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7RBA6G';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7RBA6Z';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7RBA8H';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N7PAMTS';

-- LANGKAH 3: UPDATE oki_perangkat - TAKALAR
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'FGT80FTK24014658';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XSBL00W7ND32';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTZD06C1347G';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTZD06BBL6S1';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'XTCA0090C912';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'KIT407514514CBP';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003502';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003505';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'SR20WY1003504';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2609A02532';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2609A02593';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'S9S2516A03210';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = '3013C261700077';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0DV2BGGT';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0D4770F9';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL03ZVJGK6';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL03LW6TPG';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0DT1HRLH';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0D3PQKPB';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD00C12H9K';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD01934KDH';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD00JGQXJL';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0CFGZM38';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD05HL37M4';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD08CZZ0QP';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD01SQ691P';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD01ZCBLHS';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL09PK29XS';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'WBBL0F249PB8';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD028C0V5T';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W4ZD0236MJL4';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W8YM03BG65MP';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W8YM0H8BP3JL';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W8ZD0BWL0PW2';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W8YM03D2Q1FJ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W8ZD0DNGHFCR';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'W8YM0JMRXKCZ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DYWZ';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ4N';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ5H';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ6E';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ60';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ3S';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ53';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ46';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DYXW';
UPDATE oki_perangkat SET site_id = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1), status = 'TERPAKAI' WHERE serial_number = 'N43DZ2V';

-- LANGKAH 4: INSERT oki_site_ba_template
DELETE FROM oki_site_ba_template;

-- KUPANG
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # Router Firewall - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'FGT80FTK23054198'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Router Firewall - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7TAF8N'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # Switch Distribusi - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'XSBL011ZV78T'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7TAF7G'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 2', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7TAF2H'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 3', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7TAF7S'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 4', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7TAF79'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # Switch Access - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'XTZD06B8H0P9'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Access - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7TAF9A'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'SN', 'SN # Access Point - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'WBBL0CJKR2PT'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Router Firewall - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Switch Distribusi - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Switch Access - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Kupang' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Access Point - 1', 'file', NULL, 'FOTO', 2);

-- SINJAI
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # Router Firewall - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'FGT80FTK23054167'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Router Firewall - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N4RA9PK'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # Switch Distribusi - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'XSBL010828SR'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7RBA97'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 2', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7RBA7N'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 3', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7RBA6S'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 4', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7PBUP6'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # Switch Access - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'XTCA0092TD4F'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Access - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N7RBAPW'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'SN', 'SN # Access Point - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'WBBL0D1D3JBK'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Router Firewall - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Switch Distribusi - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Switch Access - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Sinjai' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Access Point - 1', 'file', NULL, 'FOTO', 2);

-- TAKALAR
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # Router Firewall - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'FGT80FTK24014658'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Router Firewall - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N43DYWZ'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # Switch Distribusi - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'XSBL00W7ND32'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N43DZ4N'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 2', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N43DZ5H'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 3', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N43DZ6E'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Distribusi - 4', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N43DZ60'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # Switch Access - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'XTZD06C1347G'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # SFP Switch Access - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'N43DZ3S'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'SN', 'SN # Access Point - 1', 'text', (SELECT id FROM oki_perangkat WHERE serial_number = 'WBBL0DV2BGGT'), 'SCAN', 1);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Router Firewall - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Switch Distribusi - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Switch Access - 1', 'file', NULL, 'FOTO', 2);
INSERT INTO oki_site_ba_template (id_site_ba, category, template_name, template_type, default_perangkat_id, note_ba, urutan) VALUES ((SELECT id FROM oki_site_ba WHERE id_site = (SELECT id FROM oki_customer_sites WHERE site_name = 'SR - Takalar' LIMIT 1) LIMIT 1), 'FOTO EVIDEN', 'Penempatan # Access Point - 1', 'file', NULL, 'FOTO', 2);
